### ISSUE TITLE
did you forget about my mod you were gonna port

### ISSUE THREAD

**Issue by fnfporterhi** [FirePlayz132/MariosMadness#1]

**Comment by FirePlayz132** [comment]
no im still working it i just have a brain that gets side tracked alot

**Comment by fnfporterhi** [comment]
oh ok

**Comment by FirePlayz132** [comment]
when im not home i mostly work on a chromebook untill i get home then i switch to pc

**Comment by fnfporterhi** [comment]
how do you port when youre on CB? i use VS code and it crashes my chromebook memory

**Comment by fnfporterhi** [comment]
im just curious

**Comment by FirePlayz132** [comment]
when im on chomebook i do this
1. i find a base html or javascript build of the base game (i find psych engines work best) 
2. i clone it
3. i find a mod i want to port (note that if you do it this way most of the time you can only port the song and chart)
4. download that mod
this parts is very time consuming
5. start renaming and replacing assets
there better ways of doing this i just found that this is the easiest and simplest way of doing it on a chromebook
 i can make a google doc that i can go more in depth on how i do it with pics of the folders and stuff im talking about if you want.

**Comment by fnfporterhi** [comment]
yeah

make a doc pls cause i wanna bookmark

**Comment by FirePlayz132** [comment]
alright im on it

**Comment by fnfporterhi** [comment]
kk

need my email?

**Comment by FirePlayz132** [comment]
na ill just post the link to it here

**Comment by fnfporterhi** [comment]
kk

**Comment by FirePlayz132** [comment]
the guide is take alittle longer then i thought so it wont be done till later today or tomorrow

**Comment by fnfporterhi** [comment]
ok, take your time no rush
